export enum BattleStates {
  OPEN_DIALOG_1 = 1,
  OPEN_DIALOG_2 = 2,
  CHOOSE_MOVE = 3,
  MY_ATTACK_CONFIRM = 4,
  OPPONENT_ATTACK_CONFIRM = 5,
  MY_ATTACK_MISSED = 95,
  OPPONENT_ATTACK_MISSED = 96,
  OPPONENT_CHOOSE_ATTACK = 99,
  I_WIN = 82,
  OPPONENT_WIN = 81,
  CLOSE_DIALOG = 50
}
